# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/djrussell23/Documents/repos/reactor-core

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/djrussell23/Documents/repos/reactor-core

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/djrussell23/Documents/repos/reactor-core/CMakeFiles /Users/djrussell23/Documents/repos/reactor-core//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/djrussell23/Documents/repos/reactor-core/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named reactor_core_native

# Build rule for target.
reactor_core_native: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 reactor_core_native
.PHONY : reactor_core_native

# fast build rule for target.
reactor_core_native/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor_core_native.dir/build.make CMakeFiles/reactor_core_native.dir/build
.PHONY : reactor_core_native/fast

#=============================================================================
# Target rules for targets named MLForgeLib

# Build rule for target.
MLForgeLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MLForgeLib
.PHONY : MLForgeLib

# fast build rule for target.
MLForgeLib/fast:
	$(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/MLForgeLib.dir/build.make mlforge/CMakeFiles/MLForgeLib.dir/build
.PHONY : MLForgeLib/fast

#=============================================================================
# Target rules for targets named test_algorithms

# Build rule for target.
test_algorithms: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_algorithms
.PHONY : test_algorithms

# fast build rule for target.
test_algorithms/fast:
	$(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/test_algorithms.dir/build.make mlforge/CMakeFiles/test_algorithms.dir/build
.PHONY : test_algorithms/fast

#=============================================================================
# Target rules for targets named test_linear_regression

# Build rule for target.
test_linear_regression: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_linear_regression
.PHONY : test_linear_regression

# fast build rule for target.
test_linear_regression/fast:
	$(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/test_linear_regression.dir/build.make mlforge/CMakeFiles/test_linear_regression.dir/build
.PHONY : test_linear_regression/fast

#=============================================================================
# Target rules for targets named test_logistic_regression

# Build rule for target.
test_logistic_regression: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_logistic_regression
.PHONY : test_logistic_regression

# fast build rule for target.
test_logistic_regression/fast:
	$(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/test_logistic_regression.dir/build.make mlforge/CMakeFiles/test_logistic_regression.dir/build
.PHONY : test_logistic_regression/fast

#=============================================================================
# Target rules for targets named benchmarks

# Build rule for target.
benchmarks: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmarks
.PHONY : benchmarks

# fast build rule for target.
benchmarks/fast:
	$(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/benchmarks.dir/build.make mlforge/CMakeFiles/benchmarks.dir/build
.PHONY : benchmarks/fast

#=============================================================================
# Target rules for targets named profiler

# Build rule for target.
profiler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 profiler
.PHONY : profiler

# fast build rule for target.
profiler/fast:
	$(MAKE) $(MAKESILENT) -f mlforge/CMakeFiles/profiler.dir/build.make mlforge/CMakeFiles/profiler.dir/build
.PHONY : profiler/fast

bindings/reactor_bindings.o: bindings/reactor_bindings.cpp.o
.PHONY : bindings/reactor_bindings.o

# target to build an object file
bindings/reactor_bindings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor_core_native.dir/build.make CMakeFiles/reactor_core_native.dir/bindings/reactor_bindings.cpp.o
.PHONY : bindings/reactor_bindings.cpp.o

bindings/reactor_bindings.i: bindings/reactor_bindings.cpp.i
.PHONY : bindings/reactor_bindings.i

# target to preprocess a source file
bindings/reactor_bindings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor_core_native.dir/build.make CMakeFiles/reactor_core_native.dir/bindings/reactor_bindings.cpp.i
.PHONY : bindings/reactor_bindings.cpp.i

bindings/reactor_bindings.s: bindings/reactor_bindings.cpp.s
.PHONY : bindings/reactor_bindings.s

# target to generate assembly for a file
bindings/reactor_bindings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reactor_core_native.dir/build.make CMakeFiles/reactor_core_native.dir/bindings/reactor_bindings.cpp.s
.PHONY : bindings/reactor_bindings.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... MLForgeLib"
	@echo "... benchmarks"
	@echo "... profiler"
	@echo "... reactor_core_native"
	@echo "... test_algorithms"
	@echo "... test_linear_regression"
	@echo "... test_logistic_regression"
	@echo "... bindings/reactor_bindings.o"
	@echo "... bindings/reactor_bindings.i"
	@echo "... bindings/reactor_bindings.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

