#!/usr/bin/env bash
# Serve a trained GRPO adapter from ollama, without ever materialising a
# merged 30B.
#
# THE CONSTRAINT THAT PICKS THE ROUTE. The obvious pipeline -- merge the
# LoRA into the base, then re-quantize to GGUF -- cannot run on this box.
# Merging needs the base in bf16: 16 shards, 56.9 GiB, against a WSL guest
# capped at 47 GiB (`memory=48GB`). It would die in host RAM before it ever
# reached a quantizer, and on this machine a host-RAM blowout is not a
# failed job, it is the desktop (see the commit-limit arc).
#
# So nothing is merged. llama.cpp converts the ADAPTER alone -- 13.4M
# trainable parameters, ~27 MB -- into a GGUF adapter, and ollama applies
# it at load time over the base GGUF it already has. The base is never
# read, never copied and never re-quantized, so the peak footprint of this
# whole script is the adapter.
#
# The base ollama already serves (`qwen3-coder:30b`, 18.6 GB Q4_K_M) is the
# same checkpoint the adapter was trained against, which is the flywheel
# invariant: the corpus was generated BY that model, so it is the model the
# corpus can teach and the model that must serve the result.
#
# Usage:  lora_to_ollama.sh <adapter-dir> [tag]
#   adapter-dir : a PEFT output dir (adapter_model.safetensors + config)
#   tag         : ollama model name to create (default qwen3-coder-ov:30b)
set -uo pipefail

ADAPTER_DIR="${1:-}"
TAG="${2:-qwen3-coder-ov:30b}"
BASE="${OV_BASE_MODEL:-qwen3-coder:30b}"
LLAMA="${LLAMA_CPP_DIR:-$HOME/llama.cpp}"
PY="${REACTOR_TRAIN_PYTHON:-$HOME/.venvs/reactor-train/bin/python}"
OUT_DIR="${OV_GGUF_OUT:-$HOME/.jarvis/adapters}"

die() { echo "REFUSING: $*" >&2; exit 2; }

[ -n "$ADAPTER_DIR" ] || die "usage: $0 <adapter-dir> [tag]"
[ -d "$ADAPTER_DIR" ] || die "no such adapter dir: $ADAPTER_DIR"
# PEFT writes both; a dir with only a config is a run that never saved.
[ -f "$ADAPTER_DIR/adapter_config.json" ] || die "no adapter_config.json in $ADAPTER_DIR"
ls "$ADAPTER_DIR"/adapter_model.* >/dev/null 2>&1 \
  || die "no adapter_model.* in $ADAPTER_DIR -- the run saved no weights"
[ -f "$LLAMA/convert_lora_to_gguf.py" ] || die "llama.cpp tools missing at $LLAMA"
"$PY" -c "import gguf" 2>/dev/null || die "the gguf package is not importable by $PY"

# The base must ALREADY be pulled. Pulling 18.6 GB here would make a
# conversion script silently a download, and it would compete with a run
# that may still be finishing.
ollama.exe list 2>/dev/null | awk 'NR>1{print $1}' | grep -qx "$BASE" \
  || die "ollama does not have '$BASE' locally; pull it deliberately, not from here"

mkdir -p "$OUT_DIR"
STAMP=$(date +%Y%m%d-%H%M%S)
GGUF="$OUT_DIR/ov-lora-$STAMP.gguf"

echo "=== adapter -> GGUF (CPU only; the base is never loaded) ==="
echo "  adapter : $ADAPTER_DIR"
echo "  base    : $BASE (already local)"
echo "  out     : $GGUF"
# --outtype f16: an adapter is small and its whole purpose is the delta;
# quantizing a 27 MB delta saves nothing and costs precision.
"$PY" "$LLAMA/convert_lora_to_gguf.py" "$ADAPTER_DIR" \
  --outfile "$GGUF" --outtype f16 --verbose 2>&1 | tail -20
[ -f "$GGUF" ] || die "conversion produced no file"
echo "  wrote $(du -h "$GGUF" | cut -f1)"

MODELFILE="$OUT_DIR/Modelfile-$STAMP"
{
  echo "FROM $BASE"
  echo "ADAPTER $GGUF"
} > "$MODELFILE"

echo
echo "=== registering '$TAG' with ollama ==="
ollama.exe create "$TAG" -f "$MODELFILE" 2>&1 | tail -10
echo
echo "=== verify it answers ==="
ollama.exe run "$TAG" "Reply with the single word: ready" 2>&1 | head -3
echo
echo "done. Point the soak at it with:  export OV_MODEL=$TAG"
